### ISSUE TITLE
Build fails while building wheel for llama-cpp-python

### ISSUE THREAD

**Issue by chdelacr** [ParisNeo/gpt4all-ui#206]
## Expected Behavior
Builds completes

## Current Behavior
Build fails while building wheel for llama-cpp-python

## Steps to Reproduce

1. Run webui.bat
2. Build fails

## Possible Solution
Installing VS, but hopefully there's another solution

## Context
[Error log](https://hastebin.skyra.pw/refejinopi.sql)

## Screenshots
Log provided

**Comment by chdelacr** [comment]
Just installed VS 2022 with C++ compiler packages, but it didn't work. Now getting this output: https://hastebin.skyra.pw/quxinaxote.csharp

**Comment by Nyandaro** [comment]
Hi  I just tried deleting VS and reinstalling it again.
I think I got the same error, but I can't see your SQL LOG lol
According to the link I wrote in my issue #204, which was closed yesterday, VS was VS2019, not VS2022.
Doesn't work on VS2022 but compiled fine on VS2019

The important thing is
MSVC v142 vs2019 c++ x64/x86 build tool
windows 10 SDK
windows C++ CMake tool

I think it's these 3

**Comment by Nyandaro** [comment]
It's probably llama_cpp_python-0.1.51 that caused the problem
So delete it once with "pip uninstall llama-cpp-python"
It is better to newly "pip install llama-cpp-python"
Otherwise, llama-cpp-python in the Python folder may not have changed to 0.1.52

You may not need to install VS if you do this

**Comment by chdelacr** [comment]
Thanks @Nyandaro 

I'll try this and come back with results

**Comment by chdelacr** [comment]
> It's probably llama_cpp_python-0.1.51 that caused the problem So delete it once with "pip uninstall llama-cpp-python" It is better to newly "pip install llama-cpp-python" Otherwise, llama-cpp-python in the Python folder may not have changed to 0.1.52
> 
> You may not need to install VS if you do this

I got this with the pip commands, I think it's the same output from the .bat script
![image](https://github.com/nomic-ai/gpt4all-ui/assets/17386344/7d86ca75-11b3-4bb9-922f-6c0a4e557de8)

**Comment by Nyandaro** [comment]
It seems that the WEB GUI is working. Thank you for confirming.

Next time you have to match the MODEL
Actually, WEB GUI does not work with all models
Most of the items posted on the top page are not working now.
I think this is due to the recent large-scale modification of llama.cpp.
Therefore, I recognize that the MODEL that can be used in the future is the V2 version.

So from Hugging Face etc.
Select and download the new converted MODEL for GGML with CPU inference type
If you are running GPU driven, choose GPTQ with GPU inference type


For reference, I often check

https://huggingface.co/TheBloke

I use GGML type in his model

Note that it seems that the one written as V3 can not be used yet


By the way, I still don't know how to convert

**Comment by chdelacr** [comment]
@Nyandaro thanks for your help, I'll take a look at these models and check if they work. 

here might be some corrections needed as the script is looking for personalities in the root folder and not in the installations one, but that's not a big deal for now.

**Comment by ParisNeo** [comment]
The thing is that you are supposed to run the add_personality script from the root folder :) in a cmd or bash shell :)

But don't worry, I am building the personality zoo ui. Which means that you'll do all this from the main interface.
